name: Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.20.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install go
        uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v2

      - run: "go test -count 1 -bench . -benchtime 1x ./..."
      - run: "go vet ./..."
